#!/usr/bin/env python3
"""
Resume sync - keeps the inline resume in index.html in step with the PDF.

The site renders the resume twice: once as the downloadable PDF in resume/,
and once as semantic HTML inside index.html. Hand-editing both is how they
drift. This script makes the PDF the input and the HTML a build product.

    python tools/sync_resume.py ~/Downloads/NewResume.pdf

  1. copies the PDF to resume/CalvinYangResume.pdf (the stable path the site
     links to, so no href ever has to change),
  2. parses it into resume/resume.json,
  3. regenerates the block in index.html between the RESUME:AUTO markers.

Run it with no argument to re-render the HTML from resume.json alone - which
is what you want after hand-fixing anything the parser got wrong. The JSON is
the editable middle layer: never edit the generated HTML, it gets overwritten.

    python tools/sync_resume.py                 # re-render from resume.json
    python tools/sync_resume.py new.pdf --json  # parse only, inspect the JSON
    python tools/sync_resume.py --check         # non-zero exit if HTML is stale

Only dependency is pypdf (pip install pypdf), and only for the parse step -
the site itself still ships with no build step and no runtime dependencies.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"
JSON_PATH = ROOT / "resume" / "resume.json"
PDF_PATH = ROOT / "resume" / "CalvinYangResume.pdf"

START = "<!-- RESUME:AUTO START - generated by tools/sync_resume.py, do not edit by hand -->"
END = "<!-- RESUME:AUTO END -->"

# Bare label -> href, for the contact line. The PDF stores these as link
# annotations, but reading them back is fragile; a lookup table is not.
LINKS = {
    "linkedin": "https://www.linkedin.com/in/calvinyang07/",
    "github": "https://github.com/SomeHeresy",
    "youtube": "https://www.youtube.com/@SomeHeresyGaming",
    "portfolio": "https://someheresy.github.io/",
}

# Sections rendered as a definition list of "Label: value" pairs rather than
# as dated entries.
LIST_SECTIONS = {"skills"}

# Section titles as they should appear on the page. Anything not listed keeps
# the PDF's wording in sentence case.
TITLE_OVERRIDES = {
    "ACTIVITIES & LEADERSHIP": "Activities & leadership",
    "PROFESSIONAL SUMMARY": "Summary",
}


# --------------------------------------------------------------------------
# Parsing
#
# pypdf's layout extraction preserves the horizontal structure of the page,
# which is what makes this tractable: indent depth tells us what a line is,
# and a run of 3+ spaces separates the left column from the right-aligned
# date or location.
# --------------------------------------------------------------------------

COLUMN_GAP = re.compile(r"\s{3,}")
BULLET = re.compile(r"^\s*[●•·]\s*")
# A right-hand column that reads as a date range rather than a location.
DATEISH = re.compile(
    r"(19|20)\d{2}|present|expected|jan\.|feb\.|mar\.|apr\.|may|jun\.|jul\.|aug\.|sep\.|oct\.|nov\.|dec\.",
    re.I,
)


def pdf_lines(pdf: Path) -> list[str]:
    from pypdf import PdfReader

    reader = PdfReader(str(pdf))
    text = "\n".join(p.extract_text(extraction_mode="layout") for p in reader.pages)
    return [ln.rstrip() for ln in text.splitlines()]


def is_section_header(line: str) -> bool:
    """Section headers sit flush left and are set in all caps."""
    if line[:1].isspace() or not line.strip():
        return False
    body = line.strip()
    letters = [c for c in body if c.isalpha()]
    return bool(letters) and all(c.isupper() for c in letters) and len(body) < 48


# A parenthesised handle at the end of an entry heading, e.g.
# "YouTube (youtube.com/@SomeHeresyGaming)". It reads better as a link on the
# subtitle line than as part of the heading.
HEADING_LINK = re.compile(r"\s*\((\S+\.\w{2,}/\S*)\)\s*$")


def split_heading_link(heading: str) -> tuple[str, str]:
    m = HEADING_LINK.search(heading)
    return (heading[: m.start()].strip(), m.group(1)) if m else (heading, "")


def href_for(display: str) -> str:
    if display.startswith(("http://", "https://")):
        return display
    return "https://" + ("" if display.startswith("www.") else "www.") + display


def split_columns(line: str) -> tuple[str, str]:
    parts = [p.strip() for p in COLUMN_GAP.split(line.strip()) if p.strip()]
    if len(parts) == 1:
        return parts[0], ""
    return parts[0], parts[-1]


def parse_contact(line: str) -> list[dict]:
    out = []
    for raw in line.split("|"):
        label = raw.strip()
        if not label:
            continue
        if "@" in label and " " not in label:
            href = "mailto:" + label
        elif re.fullmatch(r"[\d()\-.\s+]{7,}", label):
            href = "tel:+1" + re.sub(r"\D", "", label)
        else:
            href = LINKS.get(label.lower(), "")
        out.append({"label": label, "href": href})
    return out


def parse_pdf(pdf: Path) -> dict:
    lines = pdf_lines(pdf)

    data: dict = {"name": "", "contact": [], "sections": []}
    section: dict | None = None
    entry: dict | None = None
    pending: list[str] = []

    def flush():
        nonlocal pending
        if pending and entry is not None:
            entry["bullets"].append(" ".join(pending))
        pending = []

    # Everything before the first ALL CAPS header is the letterhead.
    head, body = lines, []
    for i, ln in enumerate(lines):
        if is_section_header(ln):
            head, body = lines[:i], lines[i:]
            break
    for ln in (x.strip() for x in head):
        if not ln:
            continue
        if not data["name"]:
            data["name"] = ln
        elif not data["contact"]:
            data["contact"] = parse_contact(ln)

    for line in body:
        stripped = line.strip()
        if not stripped:
            flush()
            continue

        if is_section_header(line):
            flush()
            entry = None
            raw = stripped
            section = {
                "title": TITLE_OVERRIDES.get(raw, raw.capitalize()),
                "kind": "list" if raw.lower() in LIST_SECTIONS else "entries",
                "entries": [],
            }
            data["sections"].append(section)
            continue

        if section is None:
            continue

        indent = len(line) - len(line.lstrip())

        if BULLET.match(line):
            flush()
            pending = [BULLET.sub("", line).strip()]
            continue

        # Deeply indented, no bullet glyph: continuation of the bullet above.
        if pending and indent >= 4:
            pending.append(stripped)
            continue

        flush()

        if section["kind"] == "list":
            label, sep, detail = stripped.partition(":")
            if sep:
                section["entries"].append(
                    {"term": label.strip(), "detail": re.sub(r"\s{2,}", " ", detail.strip())}
                )
            continue

        left, right = split_columns(line)

        # A long, undated line with no entry open is prose (the old
        # professional summary sat here).
        if entry is None and not right and len(stripped) > 90:
            section.setdefault("prose", []).append(stripped)
            continue

        dated = bool(right and DATEISH.search(right))

        if entry is not None and not entry["bullets"]:
            if not entry["where"]:
                # Second line of an entry: the role, employer, or location.
                entry["where"] = " · ".join(x for x in (left, right) if x)
                continue
            if dated and not entry["when"]:
                # Education blocks put the school and its city on one line and
                # the degree and its date on the next. One entry, not two.
                entry["when"] = right
                entry["where"] = " · ".join(x for x in (left, entry["where"]) if x)
                continue

        heading, link = split_heading_link(left)
        entry = {
            "heading": heading,
            "when": right if dated else "",
            "where": "" if dated or not right else right,
            "link": link,
            "bullets": [],
        }
        section["entries"].append(entry)

    flush()
    for s in data["sections"]:
        if "prose" in s:
            s["prose"] = " ".join(s["prose"])
    return data


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------

def esc(s: str) -> str:
    return html.escape(s, quote=False)


def dashes(when: str) -> str:
    """The PDF is inconsistent about it; the page always uses an en dash."""
    return re.sub(r"\s-\s", " – ", when)


def anchor(display: str) -> str:
    return (
        '<a href="' + href_for(display) + '" target="_blank" '
        'rel="noopener noreferrer">' + esc(display) + "</a>"
    )


def render(data: dict) -> str:
    lines: list[str] = []
    add = lines.append

    add(START)
    add('        <article class="resume-doc">')
    add('          <div class="resume-doc-head">')
    add("            <h3>" + esc(data["name"]) + "</h3>")
    add('            <ul class="resume-contact">')
    for c in data["contact"]:
        label, href = esc(c["label"]), c.get("href", "")
        if not href:
            add("              <li>" + label + "</li>")
        elif href.startswith(("mailto:", "tel:")):
            add('              <li><a href="' + href + '">' + label + "</a></li>")
        else:
            add(
                '              <li><a href="' + href + '" target="_blank" '
                'rel="noopener noreferrer">' + label + "</a></li>"
            )
    add("            </ul>")
    add("          </div>")

    for section in data["sections"]:
        add("")
        add('          <div class="resume-block">')
        add("            <h4>" + esc(section["title"]) + "</h4>")
        add("            <div>")

        if section.get("prose"):
            add('              <p class="resume-summary">' + esc(section["prose"]) + "</p>")

        if section["kind"] == "list":
            add('              <dl class="resume-skills">')
            for item in section["entries"]:
                add(
                    '                <div><dt>' + esc(item["term"]) + "</dt>"
                    "<dd>" + esc(item["detail"]) + "</dd></div>"
                )
            add("              </dl>")
        else:
            for e in section["entries"]:
                add('              <div class="resume-entry">')
                head = "<h5>" + esc(e["heading"]) + "</h5>"
                if e["when"]:
                    head += '<span class="resume-when">' + esc(dashes(e["when"])) + "</span>"
                add('                <div class="resume-entry-head">' + head + "</div>")
                where = esc(e["where"]) if e["where"] else ""
                if e.get("link"):
                    link = anchor(e["link"])
                    where = (where + " · " + link) if where else link
                if where:
                    add('                <p class="resume-where">' + where + "</p>")
                if e["bullets"]:
                    add("                <ul>")
                    for b in e["bullets"]:
                        add("                  <li>" + esc(b) + "</li>")
                    add("                </ul>")
                add("              </div>")

        add("            </div>")
        add("          </div>")

    add("        </article>")
    add("        " + END)
    return "\n".join(lines)


def splice(index_html: str, block: str) -> str:
    i, j = index_html.find(START), index_html.find(END)
    if i == -1 or j == -1:
        sys.exit("error: RESUME:AUTO markers not found in " + str(INDEX))
    # Keep whatever indentation precedes the start marker.
    line_start = index_html.rfind("\n", 0, i) + 1
    indent = index_html[line_start:i]
    return index_html[:line_start] + indent + block.lstrip() + index_html[j + len(END):]


# --------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description="Sync the inline resume in index.html with the PDF.")
    ap.add_argument("pdf", nargs="?", help="new resume PDF to import")
    ap.add_argument("--json", action="store_true", help="parse to JSON only, leave HTML alone")
    ap.add_argument("--check", action="store_true", help="exit 1 if index.html is out of date")
    args = ap.parse_args()

    if args.pdf:
        src = Path(args.pdf).expanduser()
        if not src.is_file():
            sys.exit("error: no such file: " + str(src))
        data = parse_pdf(src)

        # Contact details outlive any single PDF revision, and the site swaps
        # the PDF's "Portfolio" link for YouTube. Keep what is already there.
        if JSON_PATH.exists():
            old = json.loads(JSON_PATH.read_text(encoding="utf-8"))
            if old.get("contact"):
                data["contact"] = old["contact"]
                print("kept contact line from existing resume.json")

        JSON_PATH.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        print("wrote " + str(JSON_PATH.relative_to(ROOT)))

        if src.resolve() != PDF_PATH.resolve():
            shutil.copyfile(src, PDF_PATH)
            print("copied PDF -> " + str(PDF_PATH.relative_to(ROOT)))
        if args.json:
            return 0
    else:
        if not JSON_PATH.exists():
            sys.exit("error: " + str(JSON_PATH) + " not found - pass a PDF to create it")
        data = json.loads(JSON_PATH.read_text(encoding="utf-8"))

    current = INDEX.read_text(encoding="utf-8")
    updated = splice(current, render(data))

    if args.check:
        if current != updated:
            print("index.html is out of date - run: python tools/sync_resume.py")
            return 1
        print("index.html is up to date")
        return 0

    if current == updated:
        print("index.html already up to date")
    else:
        with open(INDEX, "w", encoding="utf-8", newline="") as fh:
            fh.write(updated)
        print("updated " + str(INDEX.relative_to(ROOT)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
